version: "3.9"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
    networks:
      - local
  api-local:
    restart: on-failure
    image: api-local
    build:
      dockerfile: Local.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - local
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/wehere?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test
networks:
  local:
    driver: bridge