on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate Secret File for Environment
        run: |
          cd ./src/main/resources/config
          touch ./develop-secret.properties
          echo "${{ secrets.DEVELOP_SECRET }}" > ./develop-secret.properties
        shell: bash


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Api build and push
        uses: docker/build-push-action@v2
        with:
          file: develop.Dockerfile
          tags: ghcr.io/my-yellow-star/wehere:${{ github.sha }}
          labels: org.opencontainers.image.source=${{ github.event.repository.html_url }}
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            github_token=${{ secrets.GH_OAUTH_TOKEN }}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_DEVELOP_HOST }}
          username: ${{ secrets.AWS_DEVELOP_USERNAME }}
          key: ${{ secrets.AWS_DEVELOP_SECRET_KEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker pull ghcr.io/my-yellow-star/wehere:${GITHUB_SHA}
            sudo docker image tag ghcr.io/my-yellow-star/wehere:${GITHUB_SHA} api
            sudo docker rmi ghcr.io/my-yellow-star/wehere:${GITHUB_SHA}
            sudo docker rm -f $(sudo docker ps -qa)
            sudo docker run -d --name server -p 80:8080 api
            sudo docker image prune -f